### ISSUE TITLE
The playlist folder tree (when adding a song to a deeply nested playlist) visually overlaps, making it difficult to read

### ISSUE THREAD

**Issue by armeliens** [Astromations/Hazy#189]
When the button to add a song to a playlist is on the left, it's quite easy

<img width="1408" height="811" alt="Image" src="https://github.com/user-attachments/assets/08d264c6-32f5-4dbf-a001-9d1d618316fb" />

But when the button is on the right instead, it becomes a mess unfortunately

<img width="705" height="733" alt="Image" src="https://github.com/user-attachments/assets/d905c94f-568d-4fe5-b165-69b7d30b955b" />

**Comment by SoCuul** [comment]
Should hopefully be fixed in the latest version of Hazy, as I implemented several fixes for context menus. However, please let me know if it's still continuing for you, and I'd be happy to take another look :)

**Comment by armeliens** [comment]
Hi! With "latest version" are you talking about an upcoming one? Because as of right now, I unfortunately still have that "problem" (it's not bothering, just wanted to let you know)

These are the extensions I have installed

Spotify for Windows (64 bit)
1.2.69.449.gfda8591a
Spicetify v2.40.11
Theme: Hazy / Base
Extensions: quickQueue.js, sort-play-loader.mjs, npvAmbience.js, CoverAmbience.js, hazy.js
Custom apps: marketplace

**Comment by SoCuul** [comment]
I'll make sure to take another look 😀
